import { FolderIcon, WrenchIcon } from "lucide-react"

import type { ConnectorProvider } from "@/features/workspace/connectors/connector-types"

const theSvgIcon = (slug: string) =>
  `https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/${slug}/default.svg`

export const connectorProviders: ConnectorProvider[] = [
  {
    id: "onedrive",
    name: "OneDrive",
    kind: "Microsoft Graph",
    status: "simulated",
    phase: "V1",
    auth: "OAuth 2.0 PKCE",
    scope: "Files.ReadWrite.Selected",
    endpoint: "graph.microsoft.com/v1.0/me/drive",
    description: "Fuente prioritaria para carpetas GIS y documentos POT del usuario.",
    accent: "text-sky-500 bg-sky-500/10 border-sky-500/20",
    formats: [".geojson", ".shp", ".dxf", ".pdf", ".csv"],
    permissions: [
      "Leer archivos y carpetas seleccionadas",
      "Descargar archivos compatibles al cache local",
      "Subir resultados solo con confirmacion del usuario",
    ],
    mcpServer: "containers-mcp / microsoft-graph",
    tools: ["container_list", "container_search", "container_get", "container_sync"],
    actionLabel: "Simular login Microsoft",
    indexTargets: ["PDF", "Excel", "CSV", "GeoJSON", "Shapefile"],
    svglRoute: theSvgIcon("microsoft-onedrive"),
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    kind: "Microsoft Graph",
    status: "planned",
    phase: "V2",
    auth: "OAuth / credenciales corporativas",
    scope: "Sites.Selected + Files",
    endpoint: "sites/{site-id}/drive",
    description: "Bibliotecas corporativas, equipos de urbanismo y repositorios POT.",
    accent: "text-teal-500 bg-teal-500/10 border-teal-500/20",
    formats: [".gdb", ".zip", ".xlsx", ".pdf", ".kml"],
    permissions: [
      "Acceder a sitios o bibliotecas aprobadas",
      "Listar documentos GIS y normativos",
      "Sincronizar carpetas con cache cifrado",
    ],
    mcpServer: "containers-mcp / sharepoint",
    tools: ["container_list", "container_search", "container_get", "container_sync"],
    actionLabel: "Simular SharePoint",
    indexTargets: ["PDF", "Excel", "Listas", "GeoJSON", "Geodatabase"],
    svglRoute: theSvgIcon("microsoft-sharepoint"),
  },
  {
    id: "google-drive",
    name: "Google Drive",
    kind: "OAuth",
    status: "simulated",
    phase: "V1",
    auth: "OAuth 2.0",
    scope: "drive.file",
    endpoint: "www.googleapis.com/drive/v3/files",
    description: "Archivos compartidos seleccionados con picker y permisos minimos.",
    accent: "text-amber-500 bg-amber-500/10 border-amber-500/20",
    formats: [".geojson", ".zip", ".pdf", ".xlsx", ".csv"],
    permissions: [
      "Usar archivos creados o elegidos por el usuario",
      "Leer metadata y contenido compatible",
      "Exportar resultados a Drive si el usuario lo confirma",
    ],
    mcpServer: "containers-mcp / google-drive",
    tools: ["container_search", "container_get", "container_upload"],
    actionLabel: "Simular login Google",
    indexTargets: ["PDF", "Sheets", "Docs", "CSV", "GeoJSON"],
    svglRoute: theSvgIcon("google-drive"),
  },
  {
    id: "dropbox",
    name: "Dropbox",
    kind: "OAuth",
    status: "planned",
    phase: "V3",
    auth: "OAuth 2.0",
    scope: "files.metadata.read + files.content.write",
    endpoint: "api.dropboxapi.com/2",
    description: "Sincronizacion de carpetas GIS personales o de equipos pequenos.",
    accent: "text-blue-500 bg-blue-500/10 border-blue-500/20",
    formats: [".geojson", ".shp", ".kml", ".pdf"],
    permissions: [
      "Leer metadata de archivos",
      "Descargar contenido seleccionado",
      "Crear archivos de salida en carpetas autorizadas",
    ],
    mcpServer: "containers-mcp / dropbox",
    tools: ["container_list", "container_get", "container_upload"],
    actionLabel: "Simular Dropbox",
    indexTargets: ["PDF", "CSV", "GeoJSON", "Shapefile"],
    svglRoute: theSvgIcon("dropbox"),
  },
  {
    id: "local",
    name: "Carpeta local / red",
    kind: "Local",
    status: "simulated",
    phase: "V1",
    auth: "Permisos del sistema",
    scope: "Ruta allowlist",
    endpoint: "file:// proyecto o SMB",
    description: "Trabajo offline con carpetas del proyecto, red interna o OneDrive sync.",
    accent: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20",
    formats: [".geojson", ".shp", ".dxf", ".gdb", ".zip"],
    permissions: [
      "Seleccionar carpeta permitida por el sistema",
      "Leer archivos GIS compatibles",
      "Guardar resultados dentro del proyecto",
    ],
    mcpServer: "containers-mcp / local",
    tools: ["container_list", "container_get", "container_sync"],
    actionLabel: "Simular carpeta local",
    indexTargets: ["PDF", "Excel", "CSV", "GeoJSON", "Shapefile", "DXF"],
    fallbackIcon: FolderIcon,
  },
  {
    id: "qgis",
    name: "QGIS",
    kind: "GIS desktop",
    status: "simulated",
    phase: "V1",
    auth: "Deteccion local",
    scope: "Proyecto y capas seleccionadas",
    endpoint: "qgis-mcp / proceso local",
    description: "Detecta proyectos .qgz, capas, estilos y geoprocesos desde QGIS.",
    accent: "text-lime-600 bg-lime-500/10 border-lime-500/20",
    formats: [".qgz", ".qgs", ".shp", ".gpkg", ".geojson"],
    permissions: [
      "Abrir proyectos seleccionados",
      "Leer capas y estilos",
      "Ejecutar geoprocesos con confirmacion",
    ],
    mcpServer: "qgis-mcp",
    tools: ["open_project", "load_layer", "buffer", "export_map"],
    actionLabel: "Simular QGIS",
    indexTargets: ["Proyectos", "Capas", "Estilos", "Geoprocesos"],
    svglRoute: theSvgIcon("qgis"),
  },
  {
    id: "arcgis-pro",
    name: "ArcGIS Pro",
    kind: "GIS desktop",
    status: "planned",
    phase: "V2",
    auth: "ArcPy / licencia local",
    scope: "Proyecto .aprx seleccionado",
    endpoint: "arcpy sidecar",
    description: "Planeado para abrir proyectos .aprx, geodatabases y layouts.",
    accent: "text-cyan-600 bg-cyan-500/10 border-cyan-500/20",
    formats: [".aprx", ".gdb", ".lyrx", ".shp"],
    permissions: [
      "Abrir proyecto seleccionado",
      "Consultar geodatabases",
      "Exportar layouts con confirmacion",
    ],
    mcpServer: "arcgis-mcp / arcpy",
    tools: ["open_project", "run_geoprocess", "query_gdb", "export_layout"],
    actionLabel: "Simular ArcGIS Pro",
    indexTargets: ["Geodatabases", "Layouts", "Capas", "Geoprocesos"],
    svglRoute: theSvgIcon("arcgis"),
  },
  {
    id: "api-rest",
    name: "APIs externas",
    kind: "External API",
    status: "planned",
    phase: "V2",
    auth: "API key / OAuth",
    scope: "Endpoints allowlist",
    endpoint: "Configurable",
    description: "Integra servicios REST para catastros, datos abiertos o sistemas internos.",
    accent: "text-violet-500 bg-violet-500/10 border-violet-500/20",
    formats: ["JSON", "GeoJSON", "CSV", "XML"],
    permissions: [
      "Consultar endpoints aprobados",
      "Transformar respuestas a datos GeoNexus",
      "Indexar respuestas seleccionadas",
    ],
    mcpServer: "api-mcp",
    tools: ["api_request", "api_search", "api_to_layer"],
    actionLabel: "Simular API",
    indexTargets: ["JSON", "GeoJSON", "Registros", "Metadatos"],
    fallbackIcon: WrenchIcon,
  },
  {
    id: "s3",
    name: "S3 / MinIO",
    kind: "Object storage",
    status: "planned",
    phase: "V3",
    auth: "Access key en keychain",
    scope: "Bucket allowlist",
    endpoint: "s3.amazonaws.com / MinIO",
    description: "Buckets de datos geoespaciales, cache remoto o entornos privados.",
    accent: "text-orange-500 bg-orange-500/10 border-orange-500/20",
    formats: [".tif", ".geojson", ".zip", ".csv"],
    permissions: [
      "Usar bucket allowlist",
      "Leer objetos compatibles",
      "Subir reportes con confirmacion",
    ],
    mcpServer: "containers-mcp / object-storage",
    tools: ["container_list", "container_get", "container_upload", "container_sync"],
    actionLabel: "Simular S3 / MinIO",
    indexTargets: ["GeoTIFF", "GeoJSON", "CSV", "ZIP"],
    svglRoute: theSvgIcon("aws"),
  },
]

