ALTER TABLE messages ADD COLUMN input_tokens INTEGER DEFAULT NULL;
ALTER TABLE messages ADD COLUMN output_tokens INTEGER DEFAULT NULL;
ALTER TABLE messages ADD COLUMN total_tokens INTEGER DEFAULT NULL;
ALTER TABLE messages ADD COLUMN duration_ms INTEGER DEFAULT NULL;
ALTER TABLE messages ADD COLUMN tokens_per_second REAL DEFAULT NULL;
ALTER TABLE messages ADD COLUMN cost_usd REAL DEFAULT NULL;
ALTER TABLE messages ADD COLUMN context_window INTEGER DEFAULT NULL;
ALTER TABLE messages ADD COLUMN context_used_pct REAL DEFAULT NULL;
