import {
  BotIcon,
  BrainCircuitIcon,
  CloudIcon,
  KeyRoundIcon,
  ServerIcon,
  TerminalIcon,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export type ProviderOption = {
  id: string
  name: string
  type: "local" | "cloud" | "mcp" | "custom"
  role: "chat" | "embedding" | "tool-router"
  auth: "none" | "api-key" | "optional"
  defaultEndpoint: string
  defaultModel: string
  description: string
  icon: LucideIcon
  models: string[]
}

export const providerOptions: ProviderOption[] = [
  {
    id: "ollama",
    name: "Ollama",
    type: "local",
    role: "chat",
    auth: "none",
    defaultEndpoint: "http://localhost:11434",
    defaultModel: "",
    description: "Proveedor local offline-first detectado por puerto 11434.",
    icon: TerminalIcon,
    models: [],
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    type: "local",
    role: "chat",
    auth: "none",
    defaultEndpoint: "http://localhost:1234/v1",
    defaultModel: "",
    description: "Servidor local compatible con OpenAI API.",
    icon: TerminalIcon,
    models: [],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://openrouter.ai/api/v1",
    defaultModel: "",
    description: "Gateway multi-modelo configurable mediante API key.",
    icon: CloudIcon,
    models: [],
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://api.openai.com/v1",
    defaultModel: "",
    description: "API directa para chat, tool-calls y embeddings cloud.",
    icon: BotIcon,
    models: [],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://api.anthropic.com",
    defaultModel: "",
    description: "Proveedor cloud configurable para razonamiento y contexto largo.",
    icon: BrainCircuitIcon,
    models: [],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://generativelanguage.googleapis.com/v1beta",
    defaultModel: "",
    description: "Acceso nativo a modelos Gemini Flash y Pro con multimodalidad integrada.",
    icon: CloudIcon,
    models: [],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://api.deepseek.com/v1",
    defaultModel: "",
    description: "Proveedor de modelos optimizados para chat y programación a costo reducido.",
    icon: CloudIcon,
    models: [],
  },
  {
    id: "groq",
    name: "Groq",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://api.groq.com/openai/v1",
    defaultModel: "",
    description: "Motor de inferencia ultra rápido LPU para modelos de código abierto como Llama 3.",
    icon: CloudIcon,
    models: [],
  },
  {
    id: "cohere",
    name: "Cohere",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://api.cohere.ai/v1",
    defaultModel: "",
    description: "API de Cohere para chat, clasificación y embeddings multilingües.",
    icon: CloudIcon,
    models: [],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    type: "cloud",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "https://api.mistral.ai/v1",
    defaultModel: "",
    description: "Modelos franceses eficientes de código abierto y APIs comerciales de alto rendimiento.",
    icon: CloudIcon,
    models: [],
  },
  {
    id: "custom-api",
    name: "API compatible",
    type: "custom",
    role: "chat",
    auth: "api-key",
    defaultEndpoint: "",
    defaultModel: "",
    description: "Conecta cualquier endpoint compatible con OpenAI /v1.",
    icon: KeyRoundIcon,
    models: [],
  },
]
